### ISSUE TITLE
Lab2

### ISSUE THREAD

**Issue by zaq007** [1is0/Kulevich#1]
**Follow the codestyles, please**
https://github.com/1is0/Kulevich/blob/7d94228f448a103c2e7fde0ba694f17bc4ac515d/Lab2.cs#L8
https://github.com/1is0/Kulevich/blob/7d94228f448a103c2e7fde0ba694f17bc4ac515d/Lab2.cs#L56
https://github.com/1is0/Kulevich/blob/7d94228f448a103c2e7fde0ba694f17bc4ac515d/Lab2.cs#L57
https://github.com/1is0/Kulevich/blob/7d94228f448a103c2e7fde0ba694f17bc4ac515d/Lab2.cs#L59

**Please, don't use magic numbers (you can do it with built-in methods)**
https://github.com/1is0/Kulevich/blob/7d94228f448a103c2e7fde0ba694f17bc4ac515d/Lab2.cs#L65

**Comment by AlekseyKulevich** [comment]
Здравствуйте!
namespace исправил. Задание про время переделал

**Comment by AlekseyKulevich** [comment]
Здравствуйте!
namespace исправил. Задание про время переделал
